---
- hosts: windows
  gather_facts: no
  tasks:

    - name: Install only particular updates based on the KB numbers
      win_updates:
        category_name:
        - SecurityUpdates
        whitelist:
        - KB2267602
        # reboot: yes
        
    - name: Validate that the netlogon service has started, before running the next task
      win_reboot:
        test_command: 'exit (Get-Service -Name Netlogon).Status -ne "Running"'
