---
- hosts: WIN-wf-ansible*
  gather_facts: no
  tasks:
  
  - name: Install package dependencies
    win_chocolatey:
      name:
       - chocolatey-core.extension
       - chocolatey-windowsupdate.extension
      state: present
  
  - name: Install firefox
    win_chocolatey:
      name: firefox
      state: present
 
  - name: Install Notepad +
    win_chocolatey:
      name: notepadplusplus
      state: present
 
