---
- hosts: windows
  gather_facts: no
  tasks:

    - name: Install only particular updates based on the KB numbers
      win_updates:
        category_name:
        - SecurityUpdates
        whitelist:
#         - KB2267602
#         - KB4561608
#         - KB4558998
        - KB4569776
        #reboot: yes
        #reboot_timeout: 120
        
     - name: Reboot Now
       win_reboot:
         reboot_timeout: 120
         shutdown_timeout: 30
