---
- hosts: windows
  gather_facts: no
  tasks:
  
  - name: Install firefox
    win_chocolatey:
      name: firefox
      state: present
 
  - name: Install Git
    win_chocolatey:
      name: git
      state: present
 
