---
- hosts: windows
  gather_facts: no
  tasks:

    - name: Install only particular updates based on the KB numbers
      win_updates:
        category_name:
        - SecurityUpdates
        whitelist:
        - KB2267602
        reboot: yes
        
#     - name: Ensure we wait long enough for the updates to be applied during reboot
#       win_updates:
#         reboot: yes
#         # reboot_timeout: 3600
