---
- hosts: windows
  gather_facts: no
  tasks:
  
  - name: Install package dependencies
    win_chocolatey:
      name:
       - chocolatey-core.extension
       - chocolatey-windowsupdate.extension
      state: present
  
  - name: Install firefox
    win_chocolatey:
      name: firefox
      state: present
 
  - name: Install Git
    win_chocolatey:
      name: git
      state: present
 
