---
- hosts: windows
  gather_facts: no
  tasks:

    - name: Install only particular updates based on the KB numbers
      win_updates:
        category_name: ["CriticalUpdates", "SecurityUpdates", "UpdateRollups"]
        whitelist:
        - KB4566424
        - KB4565349
        - KB4552924
        - KB4569776
        reboot: yes
        reboot_timeout: 300
    
#     - name: Reboot Now
#       win_reboot:
#         reboot_timeout: 120
#         shutdown_timeout: 30
