---
- hosts: windows
  gather_facts: yes
  tasks:
  
  - name: Install package dependencies
    win_chocolatey:
      name:
       - chocolatey-core.extension
       - chocolatey-windowsupdate.extension
      state: present
      
  - name: remove firefox
    win_chocolatey:
      name: firefox
      state: absent
