---
- hosts: windows
  gather_facts: no
  tasks:
  - name: Install firefox,winscp,curl
    win_chocolatey:
      name: '{{ item }}'
      state: absent
    loop:
    - firefox
    - curl
    - winscp
