---
- hosts: windows
  gather_facts: no
  tasks:

    - name: Reboot a slow machine that might have lots of updates to apply
      win_reboot:
        pre_reboot_delay: 10
        reboot_timeout: 300
